# Generated by Django 3.0.6 on 2020-05-21 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0003_auto_20200522_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmuser',
            name='userfirm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='giris.Firm'),
        ),
    ]
