# Generated by Django 3.0.6 on 2020-05-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='ad',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
