# Generated by Django 3.0.6 on 2020-05-25 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musteri', '0002_auto_20200525_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
