# Generated by Django 3.0.6 on 2020-05-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0003_auto_20200525_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
