# Generated by Django 3.0.6 on 2020-05-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0004_firm2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firm2',
        ),
    ]
