# Generated by Django 3.0.6 on 2020-05-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0005_delete_firm2'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri',
            name='adres',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='musteri',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('K', 'Kadın'), ('E', 'Erkek'), ('D', 'Diğer')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='musteri',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='musteri',
            name='dog_tar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musteri',
            name='egitim',
            field=models.CharField(blank=True, choices=[('I', 'İlkokul'), ('O', 'Ortaokul'), ('L', 'Lise'), ('M', 'Önlisans'), ('U', 'Lisans')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='musteri',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='musteri',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='ad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
