# Generated by Django 3.0.6 on 2020-06-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0006_auto_20200531_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='dog_tar',
            field=models.DateField(blank=True, null=True),
        ),
    ]
